# Generated by Django 5.1 on 2024-08-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plot',
            name='plot_electricity',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='plot_garbage',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='plot_location',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='plot_map',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='plot_name',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='plot_owner',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='plot_price_description',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='plot_security',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='plot_status',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='plot_type',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='plot_water',
        ),
        migrations.AlterField(
            model_name='plot',
            name='plot_address',
            field=models.CharField(default='Thika', max_length=200),
        ),
        migrations.AlterField(
            model_name='plot',
            name='plot_price',
            field=models.PositiveIntegerField(default='10000'),
        ),
    ]
